### ISSUE TITLE
Line removal when merging pull requests

### ISSUE THREAD

**Issue by christianheinrichs** [Cutwell/Hacktoberfest-Census#1696]
@Cutwell Sorry for getting so late back to you regarding this issue.

Context: https://github.com/Cutwell/Hacktoberfest-Census/issues/1683#issuecomment-341600371 and https://github.com/Cutwell/Hacktoberfest-Census/issues/1683#issuecomment-341678063

As already mentioned in the linked comment, sometimes when merging pull requests (which in this case was done exclusively via GitHub's website and not the Git CLI), the entry of another user gets removed completely and then has to be re-added.

Following are the screenshots you requested.

Commit 76f5fde:

![Commit 76f5fde](https://i.cubeupload.com/sShwXs.png)

Commits c9f6c24 and 8cdf80f:

![Commits c9f6c24 and 8cdf80f](https://i.cubeupload.com/I28z0J.png)

What could be causing this?

**Comment by Cutwell** [comment]
Thanks for getting back to me (no worries about the delay, this issue is hardly time sensitive).
I believe that the issue stems from a few instances of PR's being merged out of series. What I mean by this is that for any pull request there will likely be at least 20+ similar pull requests all 'competing' to add a new entry onto the same line. By resolving a single one of these pull requests we now create a new version of the README.md file for new contributors to add their names to, and so on with each successive accepted pull request.
As not every pull request for a certain version of the README.md file was accepted before moving onto accepting newer pull requests, we end up with old README.md pull requests wanting to not only add their own entry to a already populated line, but also delete all / some other content added since that particular fork was made.
Because of this, adding new entries to the README.md file is made difficult, as we can no longer purely rely on the web interface to resolve these conflicts, having to instead manually resolve each individual pull request.
As for solutions, I've drawn a blank. Hacktoberfest is over and this repository finished 5th in contributions over the month, so there's little value to be gained from accepting pull requests anymore (even besides the fact that it wasn't necessary in the first place).
